[build]
  base = "product-manager"
  command = "npm run build"
  publish = "product-manager/dist/product-manager/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200